MD5 support

diff --git a/KernUP b/KernUP
--- a/KernUP
+++ b/KernUP
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-Version="0.9.9";
+Version="1.0";
 AppData="$HOME/.KernUP";
 AppName="kernup";
 AliasName="$HOME/.bash_aliases";
@@ -8,6 +8,7 @@ InstalledVersion=$(uname -r | cut -d "-" -f1 | sort -V | cut -d "." -f1,2,3 | ta
 KernelInstalled=`echo $InstalledVersion`
 Architecture=`uname -m`;
 Core_Url="https://raw.githubusercontent.com/DamiaX/KernUP/master/KernUP";
+MD5_Url="https://raw.githubusercontent.com/DamiaX/KernUP/master/kernup.md5";
 Lang_Name="KernUP.lang";
 Pass='';
 term="/dev/tty";
@@ -15,7 +16,6 @@ RunDir=`echo $PWD`;
 VboxDir='/etc/inid.d/vboxdrv'
 su='0';
 KernelVer='';
-
 
 Color()
 {
@@ -209,6 +209,20 @@ InstallApp;
 AppUpdate;
 }
 
+CheckSum()
+{
+wget $MD5_Url -q -O "$AppData/kernup.md5";
+md5sum -c 'kernup.md5';
+if [ $? == 0 ] ; then
+rm -rf "$AppData/$Lang_Name";
+rm -rf "$AppData/kernup.md5";
+bash "$AppData/$AppName";
+else
+echo -e -n "\E[$Alert;1m$Information \033[0m"; 
+echo -e "\E[$Wow;1m$Abort\033[0m"; 
+exit
+fi
+}
 AppUpdate()
 {
 Server_Version=$(wget "https://raw.githubusercontent.com/DamiaX/KernUP/master/Version" -q -O -);
@@ -219,10 +233,9 @@ then
 echo -e -n "\E[$Alert;1m$Information\033[0m"; 
 echo -e "\E[$Wow;1m $Updatelng\033[0m";
 wget $Core_Url -q -O "$AppData/$AppName" | chmod +x -f "$AppData/$AppName";
+CheckSum;
 echo -e -n "\E[$Alert;1m$Information\033[0m"; 
 echo -e "\E[$Action;1m $Rebotlng \040";
-rm -rf "$AppData/$Lang_Name";
-bash "$AppData/$AppName";
 exit;
 fi
 }
